### ISSUE TITLE
About raw data

### ISSUE THREAD

**Issue by weiWANG881108** [Kevin-Haigis-Lab/kras-allele-genetic-interactions#20]
Hi,

This is a great work. Recently, I want to repeat the work in the paper, I found that some files are missing in the linker "https://figshare.com/articles/dataset/The_origins_and_genetic_interactions_of_KRAS_mutations_are_allele-_and_tissue-specific/14115569"

for example, the file cancer-data folder in the script "20_prepare-cancer-data.R". How can I find those files.

Best,

Wei

**Comment by jhrcook** [comment]
Thank you for filing an Issue. I'm currently unable to attend to this until next week. I apologize for the inconvenience and will make sure to help you get this taken care of soon.

**Comment by jhrcook** [comment]
Thank you for your patience. I have updated the FigShare repo with more of the data files. Please let me know if you run into anymore issues and I'll do my best to assist you.
